### ISSUE TITLE
User data survives server termination

### ISSUE THREAD

**Issue by smola** [scaleway/api.scaleway.com#51]
User data survives server termination. This should be documented, since one could assume that deleting a server would delete any associated user data.

If sensibe information is stored in user data and a server is deleted, there is no easy way to check stored user data unless there old server ID is preserved, so it is easy to unadvertedly leave dangling data stored permanently.

**Comment by frivoire** [comment]
Hello,

User data *are* deleted after server deletion, but only after a delay of 30 days.
During that 30 days period, data are still available in the API (if you "remember" the uuid of the server).

In your case, you have probably tried to fetch user-data for a server that you deleted recently, and you got those user-data.
So, you assumed that we kept those data "forever" in our DBs, but it's not true.

By the way, if you store sensible information inside user-data, consider encrypting them before storing them.
It could be a good-pratice, since we (scaleway) have absolutely no need to read those data, we just store them as blobs (keys / values) linked to a server.

**Comment by smola** [comment]
@frivoire Thanks! It would be nice to document that. For me, not being permanent solves my concerns.
